### ISSUE TITLE
Ruby 1.9 - helpers.rb:111: invalid multibyte char (US-ASCII)

### ISSUE THREAD

**Issue by jonn** [cainlevy/snail#25]
For those of us still using Ruby 1.9, snail-1.2.2/lib/snail/helpers.rb could use <code># encoding: utf-8</code> at the top of the file.

**Comment by cainlevy** [comment]
easily done! thanks @jonn, try v1.2.3.

**Comment by jonn** [comment]
All good with v1.2.3, thank you @cainlevy!
