### ISSUE TITLE
Always display the country line

### ISSUE THREAD

**Issue by dbaq** [cainlevy/snail#28]
Hey @cainlevy,

Currently the `home_country` is used to determine whether we should display the country line. I believe it is too restrictive and before opening a PR, I would like to discuss with you about it.

In some cases, printing the country line is required. Think about an invoice for instance, the company address printed (`home_country`) might be different from the billing/delivery address country (destination).
For an international invoice, the company country should be printed but it is not the case since the `home_country` property is specified. Also, the `home_country` property always fallback to `US` (https://github.com/cainlevy/snail/blob/master/lib/snail.rb#L61).

To avoid breaking changes, I was thinking about adding another property, something like `skip_country_line` which will be `true` by default. You will be able to override it like `home_country`: `Snail.skip_country_line = false`

Let me know your thoughts.

Cheers.

**Comment by cainlevy** [comment]
I'd be happy for the presence of a country line to be more configurable. The hardest part might be choosing the property name! `Snail.skip_country_line` doesn't quite convey the _sometimes_ behavior.

What if:

* `Snail#country_line` always returned a value, regardless of the origin
* `Snail#to_s` becomes entirely responsible for whether the country line is present
* `Snail#to_s` accepts a `country: true` boolean that overrides the default "smart" behavior?
* `Snail#to_html` proxies kwargs through to `#to_s`

What do you think?

**Comment by dbaq** [comment]
Hahaha couldn't agree more, naming things is my daily nightmare!

I do like your solution, it is an elegant way to avoid breaking changes. The only drawback (I am not even sure it is a real one) is that the `Snail#country_line` would have a different behavior than today. I don't really see a use case for using `Snail#country_line` directly but who knows. 
Do you know if that could be a problem?

**Comment by cainlevy** [comment]
@dbaq I also have a hard time imagining a use case for accessing `Snail#country_line` directly, but perhaps the change can have some concessions to a backwards compatible transition?

**Comment by dbaq** [comment]
I'll try to open a PR by mid next week. I've been experiencing my `skip_country_line` in prod for the last two weeks and it works fine. I'll implement the solution we talked about.
