### ISSUE TITLE
Correct Italian Formatting

### ISSUE THREAD

**Issue by justinleveck** [cainlevy/snail#33]
http://www.columbia.edu/~fdc/postal/#italy

![image](https://cloud.githubusercontent.com/assets/2327754/25550563/fa4cc546-2c2e-11e7-9f31-a9cdfe0a4581.png)

**Comment by justinleveck** [comment]
It seems as though another project similar to this one https://github.com/yolk/biggs does not use parenthesis at all in any of their formats .. maybe something to consider.

**Comment by cainlevy** [comment]
Thanks for the notice. Looks like I should drop the parens from Belarus as well.

**Comment by cainlevy** [comment]
Fixed in v2.2.2
